apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nextcloud-aio-apache
  name: nextcloud-aio-apache
  namespace: "{{ .Values.NAMESPACE }}"
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: "{{ .Values.APACHE_PORT }}"
      port: {{ .Values.APACHE_PORT }}
      targetPort: {{ .Values.APACHE_PORT }}
    - name: {{ .Values.APACHE_PORT }}-udp
      port: {{ .Values.APACHE_PORT }}
      protocol: UDP
      targetPort: {{ .Values.APACHE_PORT }}
  selector:
    io.kompose.service: nextcloud-aio-apache
